[project]
name = "belajar-cicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "arief minardi", email = "ariefminardi140@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
belajar-cicd = "belajar_cicd:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
